### PR TITLE
fixes execute operation, closes #161

### LINKED ISSUE #161: "Frank Macreery executeed"
Feel free to bucketize this issue.

Incorrect auto-suffixing on activity verbs. Let's have an explicit mapping here, and while we're at it, might want to map `:execute` to "SSHed"

### PR DESCRIPTION
**Pull request by sandersonet**

### CODE REVIEW

**Comment by sandersonet** [comment]
cc @mixonic

File: tests/helpers/shared-tests.js [hunk 1]
```diff
@@ -156,11 +156,13 @@ export function resourceOperationsTest(options){
 
     equal(operations.length, 3, 'has 3 operations');
 
-    ['configure', 'deploy', 'execute'].forEach(function(type){
+    ['configure', 'deploy'].forEach(function(type){
       ok(find('.operation-type:contains(' + type + 'ed)').length,
          'has capitalized operation type: ' + type);
     });
 
+    ok(find('.operation-type:contains(SSHed)').length, 'converts execture to SSH');
```
Comment (mixonic) [inline tests/helpers/shared-tests.js]: `converts executed`

**Comment by mixonic** [comment]
small nit, then please merge when you are ready.
